FROM --platform=${BUILDPLATFORM} registry.access.redhat.com/ubi8/ubi:latest

ARG S3FS_VERSION=v1.88
ARG TARGETARCH

WORKDIR /

COPY hack/docker/s3fs-build /usr/local/bin/s3fs-build

RUN /usr/local/bin/s3fs-build ${TARGETARCH} ${S3FS_VERSION}

RUN rm usr/local/bin/s3fs-build
