
FROM --platform=${BUILDPLATFORM} golang:1.15-alpine as dummy

FROM registry.access.redhat.com/ubi8/ubi:latest

WORKDIR /

RUN yum remove -y fuse fuse-s3fs
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN yum install -y s3fs-fuse
RUN yum remove -y epel-release
RUN yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical

RUN echo "user_allow_other" > /etc/fuse.conf
