apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: csi.marketplace.redhat.com
spec:
  volumeLifecycleModes:
  - Ephemeral
  - Persistent
  attachRequired: false
  podInfoOnMount: true