apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-rhm-cos-pvc
  annotations:
    csi.marketplace.redhat.com/buckets: "all"
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-rhm-cos