#!/bin/sh
set -x

useradd -m ${USER_NAME} && echo "${USER_NAME}:${USER_NAME}" | chpasswd
sed -i "/Defaults \+secure_path/s/.*/Defaults\tsecure_path = \/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin/" /etc/sudoers
echo "${USER_NAME} ALL=(ALL:ALL) NOPASSWD:ALL" | sudo EDITOR="tee -a" visudo

# ensure $HOME exists and is accessible by group 0 (we don't know what the runtime UID will be)
mkdir -p ${HOME}
chown ${USER_UID}:0 ${HOME}
chmod ug+rwx ${HOME}

# runtime user will need to be able to self-insert in /etc/passwd
chmod g+rw /etc/passwd

# no need for this script to remain in the image after running
rm $0